### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by qdm12**
I am Quentin Mc Gaw, a software engineer working the Go Polkadot host **Gossamer**. I have been working full time on Gossamer since October 2021, mostly on the state trie and storage. I have also made a [few minor pull requests](https://github.com/w3f/polkadot-spec/pulls?q=is%3Apr+is%3Aclosed+author%3Aqdm12) to the Polkadot specification repository.

I am requesting to join the Fellowship at rank 1.

### Gossamer

- Fix memory leaks
  - Trie encoding buffer pools usage fixed [#2009](https://github.com/ChainSafe/gossamer/pull/2009)
  - Fix state map of tries memory leak [#2286](https://github.com/ChainSafe/gossamer/pull/2286)
  - Fix sync benchmark [#2234](https://github.com/ChainSafe/gossamer/pull/2234)
- Trie proof fixes ([#2604](https://github.com/ChainSafe/gossamer/pull/2604), [#2661](https://github.com/ChainSafe/gossamer/pull/2661))
- Fix end to end tests orchestration ([#2470](https://github.com/ChainSafe/gossamer/pull/2470), [#2452](https://github.com/ChainSafe/gossamer/pull/2452), [#2385](https://github.com/ChainSafe/gossamer/pull/2385), [#2370](https://github.com/ChainSafe/gossamer/pull/2370))
- State trie statistics ([#2378](https://github.com/ChainSafe/gossamer/pull/2378), [#2310](https://github.com/ChainSafe/gossamer/pull/2310), [#2272](https://github.com/ChainSafe/gossamer/pull/2272))
- State trie fixes and improvements
  - Only deep copy nodes when mutation is certain [#2352](https://github.com/ChainSafe/gossamer/pull/2352) and [#2223](https://github.com/ChainSafe/gossamer/pull/2223)
  - Only deep copy necessary fields of a node [#2384](https://github.com/ChainSafe/gossamer/pull/2384)
  - Use Merkle values for database keys instead of always hash [#2725](https://github.com/ChainSafe/gossamer/pull/2725)
  - Opportunistic parallel Merkle value commputing [#2081](https://github.com/ChainSafe/gossamer/pull/2081)
- Grandpa capped number of tracked messages ([#2490](https://github.com/ChainSafe/gossamer/pull/2490), [#2485](https://github.com/ChainSafe/gossamer/pull/2485))
- Add pprof HTTP service for profiling [#1991](https://github.com/ChainSafe/gossamer/pull/1991)

Ongoing work:

- State trie lazy loading and caching
- State trie v1 support ([#2736](https://github.com/ChainSafe/gossamer/pull/2736), [#2747](https://github.com/ChainSafe/gossamer/pull/2747), [#2687](https://github.com/ChainSafe/gossamer/pull/2687), [#2686](https://github.com/ChainSafe/gossamer/pull/2686), [#2685](https://github.com/ChainSafe/gossamer/pull/2685), [#2673](https://github.com/ChainSafe/gossamer/pull/2673), [#2611](https://github.com/ChainSafe/gossamer/pull/2611), [#2530](https://github.com/ChainSafe/gossamer/pull/2530))

### Polkadot specification

➡️ [Pull requests from qdm12](https://github.com/w3f/polkadot-spec/pulls?q=is%3Apr+is%3Aclosed+author%3Aqdm12)

### CODE REVIEW

**Comment by andresilva** [comment]
Nice to see your application, hopefully we get more PRE implementers to apply! :-)

**Review by andresilva — APPROVED** [review]

**Review by jacogr — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by rrtti — APPROVED** [review]

**Comment by rrtti** [comment]
@qdm12 please provide a Kusama format address, thanks!

**Comment by rrtti** [comment]
Hello @qdm12! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

**Comment by qdm12** [comment]
Hi Raul, sorry for the delay answering; My element handle: `@qqqninja:matrix.org`, let me know if you need my Kusama address in another format.

**Pull request merged**
