### PR TITLE
Member request

### PR DESCRIPTION
**Pull request by seunlanlege**
I'm humbly requesting to be added as rank ~Dan III~ (since centauri isn't live yet), Dan II. 

I joined parity in 2018, where I got started by working on the parity-ethereum client, But switched teams in 2019 from parity-ethereum to the substrate client team. Where i've made contributions to core pieces of substrate chains ranging from consensus, rpc, transaction pool, simulation testing (manual-seal which is used by parachain teams like moonbeam, astar and acala) and api design.

### Pull requests to substrate here:

https://github.com/paritytech/substrate/pulls?page=1&q=is%3Apr+author%3Aseunlanlege+is%3Amerged

### Featurettes on substrate seminar

https://www.youtube.com/watch?v=uhkV0jAcWDY
https://www.youtube.com/watch?v=0FvcABti7yk

### Working in the parachain ecosystem

After leaving parity in 2021, I joined composable.finance where i lead the team responsible for the research and design of trustless bridges where we've implemented:

 - [x] Both a beefy and grandpa light client for the IBC protocol here: https://github.com/ComposableFi/centauri
- [x] IBC protocol implementation for substrate chains here: https://github.com/ComposableFi/composable/blob/centauri/code/parachain/frame/ibc/src/lib.rs
- [x] Chain agnostic IBC relayer implementation: https://github.com/ComposableFi/hyperspace

### Technical writing related to trustless bridging

https://medium.com/composable-finance/trustless-bridging-438a6e5c917a
https://medium.com/composable-finance/trustless-bridging-ii-byzantine-fault-tolerance-591e8b2d196e

This work will be used to bridge our picasso (kusama) parachain to our composable (polkadot) parachain, as well as bridge our parachains to NEAR, cosmos-sdk chains and ethereum and its rollups.

### Hobby Projects

In my spare time i like to hack on simulation testing, where i continue to maintain a simulation testing framework for substrate based on manual-seal here: 

https://github.com/polytope-labs/substrate-simnode

### CODE REVIEW

**Comment by rphmeier** [comment]
Based on prior contributions while at Parity, I would have thought II Dan is appropriate. However, I believe that the requirements for III Dan would be met specifically with the inclusion of the 'centauri' light-client bridge to IBC, which is covered in the Manifesto in Section 2.4

> Thirdly, we include the Polkadot business-logic (aka the “runtime”), including frame internals, runtime and host
apis, pallets utilised by Polkadot and its system chains. Finally, we also cover expertise concerning xcm, grandpa-based
bridges and standard RPCs.

And combined with the III Dan requirements:

> becoming
a Fellow indicates the individual has enough knowledge and skill to build
substantial protocol components (i.e. all but the major protocol components,
e.g. a pallet or 2-10,000 line crate) alone and with high expectations that they
will be completed correctly and to a high standard

I am on the fence, primarily because the `centauri` bridge has not launched yet and therefore it's not clear that it has been completed _correctly_. That said, it's an impressive contribution and I do believe merits III Dan.

From where I sit, II Dan is a clear 'yes' and III Dan is a 'pending deployment of Centauri in the real world', but I could be swayed by a positive audit report + demonstration of a testnet deployment. The public writing, public presentation, and high-level approach requirements are met in my opinion.

**Comment by gavofyork** [comment]
Manifesto (draft 3) section 2.3.1 includes:

> trust-free bridges relying on said consensus algorithms (planned to be) utilised by system chains;

While it appears that Centauri is indeed trust-free, it doesn't appear to be (even planned to be) deployed into a system chain? It seems it's mostly introducing components into other ecosystem to allow them to track Polkadot finality. This is interesting, important and valuable work, but it doesn't appear to fit the definition of "expertise on technology and code which is required by, and primarily utilised for, the Polkadot (Main) Network".

Aside from this I'd say that requirements for III Dan seem to be fulfilled. Is there any expectation that a substantial component of Centauri will eventually be deployed within a system chain?

**Comment by seunlanlege** [comment]
> Is there any expectation that a substantial component of Centauri will eventually be deployed within a system chain?

Yes, centauri is in it's final stages of development, we're already auditing the [grandpa light client](https://github.com/ComposableFi/centauri/blob/master/light-clients/ics10-grandpa/src/lib.rs), [pallet-ibc](https://github.com/ComposableFi/composable/blob/centauri/code/parachain/frame/ibc/src/lib.rs) and [ibc-rs](https://github.com/ComposableFi/ibc-rs). 

pallet-ibc will be deployed to rococo before mid-october, we're targetting end of october for mainnet launch.

**Comment by rrtti** [comment]
Based on the discussion about pallet-ibc and Centauri, I think II Dan would be more suitable for the submission: as stated, Centauri has not launched yet and therefore it's not clear that it has been completed correctly, as per the comments above. For approval, II Dan requirements are fulfilled - @seunlanlege could you edit the application to II Dan position?

**Comment by seunlanlege** [comment]
@rrtti I've changed the rank

**Review by bkchr — APPROVED** [review]

**Review by jacogr — APPROVED** [review]

**Review by rphmeier — APPROVED** [review]

**Review by rrtti — APPROVED** [review]

**Comment by rrtti** [comment]
@seunlanlege can you provide a KSM address in the right format? Thank you.

**Comment by seunlanlege** [comment]
Sorry about this, i've created a [new PR here](https://github.com/polkadot-fellows/seeding/pull/59) for this

**Pull request merged**
