### PR TITLE
Polkadot Fellow application

### PR DESCRIPTION
**Pull request by MrishoLukamba**
I am Mrisho Lukamba and I am humbly applying for Polkadot fellowship due to the following reasons:
My contributions are all non-trivial ( I think ). 
1. https://github.com/paritytech/substrate/pull/12289 -> This Pr was finished by @Ankan as you can see in the comments we co-authored the commits
 The following Pr are approved waiting to be merged
1. https://github.com/paritytech/substrate/pull/12084
2. https://github.com/paritytech/substrate/pull/12509

The following is the issue am working on at the moment
https://github.com/paritytech/substrate/issues/12484 , my bad someone took it already

I am also working on my project which will introduce a new payment verification method. Am using substrate and will also dive into light clients implementation ( native)
https://github.com/2-5-Foundation/Vane-Trustless-Payment

I also worked with Fair Squares project as a substrate runtime developer which received Grant from web3 Foundation.
https://github.com/Fair-Squares/fair-squares

I am also helping beginners to onboard into substrate and answering questions inside stack-exchange. These all hopefully showing commitment and level of expertise for me to apply for Dan 1.
My substrate contributions will keep growing as I want to make substrate easy to onboard but the best framework possible.
Kindly consider me.

### CODE REVIEW

**Comment by bkchr** [comment]
Hey @MrishoLukamba,
I would really like to see you here in the fellowship. However, before approving I would really like to see some substantial contributions. The contributions you have listed so far are relative trivial changes that didn't require any deep knowledge of any pallet implementation etc.

Nevertheless, if you follow your current path, I think that you will make it!!

**Comment by MrishoLukamba** [comment]
> Hey @MrishoLukamba, I would really like to see you here in the fellowship. However, before approving I would really like to see some substantial contributions. The contributions you have listed so far are relative trivial changes that didn't require any deep knowledge of any pallet implementation etc.
> 
> Nevertheless, if you follow your current path, I think that you will make it!!

Thanks Bastian , so i think i will keep the Pr open and update my application as I contribute more. What do you think?

**Comment by bkchr** [comment]
Sounds good! :+1:

**Comment by rrtti** [comment]
@MrishoLukamba Agree with @bkchr: take into account that as we prepare for deployment of gov2, the seeding will close and you will also be able to apply on-chain once your contributions are ready (if these are not ready before). If you believe you are a protocol expert and long-term active core developer, please provide details of your three earliest **substantial** PRs to a Polkadot core repository (Substrate, Polkadot, Cumulus) as well as a list of any significant design and development contributions to core code. 

Other instances of the Fellowship are expected for ecosystem participants who are not protocol experts or long-term active core developers.

**Pull request closed without merging**
