### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by kishansagathiya**
Hi,

I'm Kishan, and I have been directly contributing to Gossamer since September 2021.

At gossamer, though I have worked on most parts of the codebase, much of my work has been implementing parts of Grandpa and Babe Protocol and fixing bugs in that part of code.

Grandpa:
- https://github.com/ChainSafe/gossamer/pull/2497
- https://github.com/ChainSafe/gossamer/pull/2486
- https://github.com/ChainSafe/gossamer/pull/2468
- https://github.com/ChainSafe/gossamer/pull/2107
- https://github.com/ChainSafe/gossamer/pull/2152

Babe:
- https://github.com/ChainSafe/gossamer/pull/2307
- https://github.com/ChainSafe/gossamer/pull/2815
- https://github.com/ChainSafe/gossamer/pull/2827
- https://github.com/ChainSafe/gossamer/pull/2596
- https://github.com/ChainSafe/gossamer/pull/2709
- https://github.com/ChainSafe/gossamer/pull/2566
- https://github.com/ChainSafe/gossamer/issues/2597
- https://github.com/ChainSafe/gossamer/issues/2682
- https://github.com/ChainSafe/gossamer/issues/2680
- https://github.com/ChainSafe/gossamer/issues/2853

I have a great understanding of Babe and Grandpa protocols. Apart of these, I have worked on other parts as well, such as scale encoding, block storage, networking, etc. I understand those pieces of code and specs reasonably well too. A decent amount of my work has involved fixing bugs and testing interoperability with polkadot and finding bug.

All of my contributions can be seen at https://github.com/pulls?q=author:kishansagathiya+user:chainsafe

After going through the menifesto, I feel like `I Dan` might describe me best.

### CODE REVIEW

**Comment by rphmeier** [comment]
Based on time I would suggest a I Dan application. The pattern of contributions seems to be a collection of small-medium improvements, which require protocol knowledge. Well on the way to II Dan.

**Comment by kishansagathiya** [comment]
> Based on time I would suggest a I Dan application. The pattern of contributions seems to be a collection of small-medium improvements, which require protocol knowledge. Well on the way to II Dan.

changed to 1

**Review by jacogr — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Review by rphmeier — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by rrtti** [comment]
Hi @kishansagathiya, please provide us with a Kusama format address for the seeding. Thank you.

**Comment by rrtti** [comment]
Hello @kishansagathiya! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

**Comment by rrtti** [comment]
Hello @kishansagathiya! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

**Comment by kishansagathiya** [comment]
@rrtti should be `@kishanmsagathiya:matrix.org`

**Pull request merged**
