### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by edwardmack**
My name is Edward Mack and I am a software engineer for Gossamer, a Golang implementation of the Polkadot Host. I have been directly contributing to Gossamer and the Polkadot ecosystem since July of 2019.

During this time I've been involved with implementing aspects of the Polkadot Host Specification for the Gossamer client, including working with BABE, GRANDPA, RPC implementation, SCALE codec, networking and interfacing with the Polkadot runtime.  I enjoy working with the Polkadot runtime -  learning and implementing interfaces for interacting with runtimes has been rewarding because I've grown to appreciate the power of having a portable, upgradable runtime.  I'm interested in joining the Fellowship to share my understanding with the community as well as being a part of shaping how Polkadot is implemented.

I am requesting to join the Fellowship at rank 1.

All of my contributions can be seen at https://github.com/ChainSafe/gossamer/pulls?q=author:edwardmack+user:chainsafe and notable contributions are listed below.

### Scale:
- https://github.com/ChainSafe/gossamer/pull/2708
- https://github.com/ChainSafe/gossamer/pull/2683
- https://github.com/ChainSafe/gossamer/pull/597
- https://github.com/ChainSafe/gossamer/pull/560

### Babe:
- https://github.com/ChainSafe/gossamer/pull/2632
- https://github.com/ChainSafe/gossamer/pull/1910

### Grandpa:
- https://github.com/ChainSafe/gossamer/pull/2624
- https://github.com/ChainSafe/gossamer/pull/2618
- https://github.com/ChainSafe/gossamer/pull/1084

### RPC
- https://github.com/ChainSafe/gossamer/pull/1574
- https://github.com/ChainSafe/gossamer/pull/1415
- https://github.com/ChainSafe/gossamer/pull/1376
- https://github.com/ChainSafe/gossamer/pull/1310
- https://github.com/ChainSafe/gossamer/pull/1290
- https://github.com/ChainSafe/gossamer/pull/1140
- https://github.com/ChainSafe/gossamer/pull/983
- https://github.com/ChainSafe/gossamer/pull/896
- https://github.com/ChainSafe/gossamer/pull/880
- https://github.com/ChainSafe/gossamer/pull/877
- https://github.com/ChainSafe/gossamer/pull/853
- https://github.com/ChainSafe/gossamer/pull/849
- https://github.com/ChainSafe/gossamer/pull/836
- https://github.com/ChainSafe/gossamer/pull/835
- https://github.com/ChainSafe/gossamer/pull/816
- https://github.com/ChainSafe/gossamer/pull/765
- https://github.com/ChainSafe/gossamer/pull/752
- https://github.com/ChainSafe/gossamer/pull/745

### Implementing runtime imports:
- https://github.com/ChainSafe/gossamer/pull/1912
- https://github.com/ChainSafe/gossamer/pull/1878
- https://github.com/ChainSafe/gossamer/pull/1821
- https://github.com/ChainSafe/gossamer/pull/1799
- https://github.com/ChainSafe/gossamer/pull/1739
- https://github.com/ChainSafe/gossamer/pull/1120
- https://github.com/ChainSafe/gossamer/pull/1118
- https://github.com/ChainSafe/gossamer/pull/1117
- https://github.com/ChainSafe/gossamer/pull/1110
- https://github.com/ChainSafe/gossamer/pull/1108
- https://github.com/ChainSafe/gossamer/pull/1101
- https://github.com/ChainSafe/gossamer/pull/1100
- https://github.com/ChainSafe/gossamer/pull/296

### Telemetry:
- https://github.com/ChainSafe/gossamer/pull/1618
- https://github.com/ChainSafe/gossamer/pull/1597
- https://github.com/ChainSafe/gossamer/pull/1528

## Community Engagement:
- [Gossamer Update: November 2020](https://blog.chainsafe.io/gossamer-update-november-2020-c8d00327b68b)
- [Gossamer Update: September 2020](https://blog.chainsafe.io/gossamer-update-september-2020-c00d1c47d3aa)

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by andresilva — APPROVED** [review]

**Review by jacogr — APPROVED** [review]

**Comment by gavofyork** [comment]
Only rank 1?

**Review by gavofyork — APPROVED** [review]
Given the wealth of contributions and the time involved, a higher rank may be deserved.

**Comment by bkchr** [comment]
> Given the wealth of contributions and the time involved, a higher rank may be deserved.

I also already thought about this. Given the time etc I would also think a higher rank is deserved, I can just not speak based on the code contributions.

**Comment by edwardmack** [comment]
Thank you so much for the kind words - I'm looking forward to participating in the Fellowship. If it's possible to elevate my rank to 2 before the close of the seeding phase, I would certainly embrace the responsibility. If that's not possible at this time, what activities should I focus on to achieve that goal?

**Comment by bkchr** [comment]
@edwardmack doing a pr to bump your rank should be enough.

**Comment by rrtti** [comment]
@edwardmack please answer here with your Element handle to confirm access to the channel. Thank you!

**Comment by edwardmack** [comment]
@rrtti my Element handle is @mackcom:matrix.org.  Thank you!

**Pull request merged**
