### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by arrudagates**
### About me:

I am the co-founder and Head of Development at https://github.com/InvArch and have had my fair share of contributions in the parachain world. I started my substrate journey in June 2021 and would like to have more meaningful code contributions to the core Polkadot protocols, which is why I'm proposing my rank start at 1.

### Rank range:

From the requirements and descriptions in the Manifesto, I believe the range from 1 to 2 would be best suited for me at this moment.

### Earliest reference/most substantial:

I believe this might be the earliest pull-request in a core repository besides parachain development: https://github.com/paritytech/smoldot/pull/2686

### CODE REVIEW

**Comment by rphmeier** [comment]
I support @arrudagates for I Dan - he is an active community member with high availability, with some upstream contributions, and a broad level of protocol knowledge.

**Review by rrtti — APPROVED** [review]

**Comment by rrtti** [comment]
Hi Gabriel! Good to see you here! Some notes: according to the Manifesto section 6.2, to attain the rank of I Dan:

> The Candidate should have made three clear demonstrations of protocol expertise. Possible examples of this may be: identifying and fixing a non-trivial protocol issue; being available and playing a crucial operational role for a network fix; proposing a reasonable and non-trivial protocol innovation; or doing a valuable, innovative and insightful refactoring or alteration.

Furthermore, section 6.2.1 states these specific requirements for I Dan:

Requirements:

> Primarily designed and implemented a minor or auxilliary component.
> Should be able to list all key goals/principles/tenets of project philosophy and how these relate to technology

Could you provide specific details on the three clear demonstrations of Polkadot protocol expertise, and the Polkadot core component you primarily designed and implemented? I might be missing them here. Thank you!

**Review by gavofyork — APPROVED** [review]

**Review by jacogr — APPROVED** [review]

**Review by rphmeier — APPROVED** [review]

**Comment by rrtti** [comment]
Hello @arrudagates! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

**Comment by arrudagates** [comment]
> Hello @arrudagates! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

Hey, my matrix handle is arrudagates:mozilla.org

**Pull request merged**
