### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by KiChjang**
I am Keith Yeung, a core runtime developer at Parity Technologies, and have been at this role for about a year and a half by now.

Most of my contributions are code-related, but I was fortunate enough to have been invited to talk at a substrate seminar before: https://www.crowdcast.io/e/substrate-seminar/44. I had also been invited to talk on the topic of XCM in the first round of the Polkadot Blockchain Academy, but alas I don't believe its lectures are open to public.

# Earliest non-trivial PR
 https://github.com/paritytech/substrate/pull/8602

# Most substantial PRs
https://github.com/paritytech/substrate/pull/8635
https://github.com/paritytech/substrate/pull/8801
https://github.com/paritytech/substrate/pull/8949
https://github.com/paritytech/substrate/pull/9225
https://github.com/paritytech/substrate/pull/11257
https://github.com/paritytech/substrate/pull/11818
https://github.com/paritytech/polkadot/pull/3404

I'm also one of the top all-time users answering XCM questions on StackExchange, and these are two of my most upvoted answers:
https://substrate.stackexchange.com/questions/37/how-can-i-transfer-assets-using-xcm/38
https://substrate.stackexchange.com/questions/591/what-is-the-difference-between-xcm-and-xcmp/592 

Given the contributions above, I think I'm most suited for III Dan, but am already on my way to IV Dan.

### CODE REVIEW

**Comment by rphmeier** [comment]
@KiChjang 

I support for III Dan, but for IV Dan I would want to see much more high-level ideation and protocol design around XCM or other protocol components.

**Review by rphmeier — APPROVED** [review]

**Review by rrtti — APPROVED** [review]

**Comment by rrtti** [comment]
Manifesto sections 6.3, 6.4, 6.5 and 6.6 all state that a time period of 12 months should generally be expected to have elapsed since attaining the prior rank, leading to a reasonable minimum period of 1 year since fulfilling I Dan requirements for attaining II Dan, 2 years since fulfilling I Dan requirements for attaining III Dan and so on.

Finally, for a rank higher and I Dan, please ensure that all requirements set out in the Manifesto for that rank and any prior ranks have been met and are clearly demonstrated. Please note that for III Dan and higher, a high degree of availability for the network must have been demonstrated. Make sure to note that becoming a Fellow indicates the individual has enough knowledge and skill to build substantial protocol components (i.e. all but the major protocol components, e.g. a pallet or 2-10,000 line crate) alone and with high expectations that they will be completed correctly and to a high standard. They should be able and willing to support that which they built given that it is running 24/7 on a public network.

**Review by bkchr — APPROVED** [review]

**Comment by KiChjang** [comment]
Note that due to time requirements, I am now instead aiming for II Dan.

**Review by jacogr — APPROVED** [review]

**Comment by rphmeier** [comment]
Approved for II Dan

**Pull request merged**
