### PR TITLE
Membership Request

### PR DESCRIPTION
**Pull request by samelamin**
Membership Request

Hi, I'm Sam Elamin. I have been working on Polkadot-based chains for close to 2 years now. 

While I have not directly contributed to Substrate Repos, Similar to [Gabe](https://github.com/polkadot-fellows/seeding/pull/2)  I have essentially launched 2 chains to Kusama almost single-handedly so consider myself somewhat familiar with the Substrate framework.

I am currently leading Imbue Network whose [code](https://github.com/imbuenetwork/imbue) is all open source

Additionally, I founded the Substrate [Devs](https://t.me/substratedevs) channel on Telegram which is a great resource for educating new developers and getting them up to speed. This channel is bridged to Matrix and has many subject matter experts from Parity

I am a very passionate and keen advocate of interoperability and I feel I can add value in guiding that vision to fruition.

My Contributions are mostly:

Education around substrate throughout the ecosystem
Discussions on Forum
Polkadot and substrate advocate who is very active in the community
Runtime development for parachains

Educational content

Activity on StackExchange answering and asking questions
https://substrate.stackexchange.com/users/18/sam-elamin

I want to apply for rank 1

### CODE REVIEW

**Comment by rrtti** [comment]
Hi @samelamin, thank you for posting this! 

As a protocol expert and long-term active core developer, please provide details of your substantial PRs to a Polkadot core repository (Substrate, Polkadot, Cumulus) as well as a list of any significant design and development contributions to core code. 

Other instances of the Fellowship are expected for ecosystem participants who are not protocol experts or long-term active core developers.

**Comment by samelamin** [comment]
Hi @rrtti  unfortunately, I haven't had a chance to contribute to the 3 core repositories very similar to Gabe on this similar membership [request](https://github.com/polkadot-fellows/seeding/pull/2)

But I feel have demonstrated enough knowledge around Substrate and expanding the ecosystem through developer adoption to warrant acceptance into Dan 1

**Comment by gavofyork** [comment]
Hi; thanks for your contributions into the ecosystem! The Fellowship is for recognising and incentivising *core* technology contributions and we have quite clear guidelines on what is considered core.

Please see the expectations written in the Fellowship Manifesto for rank 1 in section 6.2:

> The Candidate should have made three clear demonstrations of protocol expertise. Possible examples of this may be: identifying and fixing a non-trivial protocol issue; being available and playing a crucial operational role for a network fix; proposing a reasonable and non-trivial protocol innovation; or doing a valuable, innovative and insightful refactoring or alteration.

Core technology includes (section 2.3.1)...
```
• the internals of all functional Polkadot node implementations;
• cryptographic data-structures, algorithms, languages and apis required for the continued upkeep of the Polkadot
(Main) Network;
• consensus algorithms concerning the Relay-chain (babe & grandpa);
• trust-free bridges relying on said consensus algorithms (planned to be) utilised by system chains;
• parachain consensus;
• cross-chain message passing (xcmp, hrmp, dmp & ump);
• the Polkadot libp2p-based peer networking protocol;
• the Polkadot topology strategies;
• chain synchronisation strategies utilised by Polkadot;
• the Polkadot business-logic (aka the “runtime”);
• pallets utilised by the Polkadot (Main) Network and its system chains;
• the internals of the frame pallet framework;
• runtime and host apis;
• the xcm specification and realisation;
• standard rpcs;
• user-interface code required to practically execute upgrades to the Polkadot (Main) Network; and
• code or technology required by, and utilised primarily for, any code or technology already included.
```

Note that Smoldot is a "functional Polkadot node implementation" and therefore contributions to it would be relevant here.

Thanks!

**Comment by samelamin** [comment]
@gavofyork Thanks for your update. While I am disappointed given the change made to Smoldot, I understand your point of view

Given I am yet to contribute to any of the core components I shall close this PR and re-open it at such time when I have met some of the requirements

Thank you so much for taking the time to review my request!

**Comment by samelamin** [comment]
reopening this pr after contributing to a few of the core repos

https://github.com/paritytech/cumulus/pull/1909

https://github.com/paritytech/polkadot/pull/6334

https://github.com/paritytech/substrate/pull/12761

https://github.com/paritytech/zombienet/pull/723

https://github.com/paritytech/zombienet/pull/673


I hope these now qualify me for rank 1

**Comment by bkchr** [comment]
Seeding is over, new members will need to apply via on chain.

**Comment by samelamin** [comment]
ah ok I will apply on chain then. Are there any docs/guides?

**Comment by bkchr** [comment]
Not that I'm aware of, maybe @rrtti knows something?

**Comment by ggwpez** [comment]
Welcome to the Fellowship!  
(he was added on-chain)

**Pull request closed without merging**
