### PR TITLE
Member Request

### PR DESCRIPTION
**Pull request by koute**
Hi.

I'm Jan, and I have been directly contributing to Polkadot (counting from my first PR) since July 2021.

My main contributions are in the area of performance, and anything and everything WASM-related, but I also try to dabble in other areas too from time to time.

### First PR

https://github.com/paritytech/polkadot/pull/3519 (a memory leak fix in Polkadot)

### Notable PRs

A lot of PRs improving performance:
- https://github.com/paritytech/substrate/pull/9933
- https://github.com/paritytech/substrate/pull/9981
- https://github.com/paritytech/substrate/pull/10191
- https://github.com/paritytech/substrate/pull/10839
- https://github.com/paritytech/substrate/pull/10859
- https://github.com/paritytech/substrate/pull/10875
- https://github.com/paritytech/substrate/pull/11523

A lot of PRs related to the WASM executor:
- https://github.com/paritytech/substrate/pull/10480
- https://github.com/paritytech/substrate/pull/10741
- https://github.com/paritytech/substrate/pull/11107
- https://github.com/paritytech/substrate/pull/11189
- https://github.com/paritytech/substrate/pull/11856
- https://github.com/paritytech/substrate/pull/10173
- https://github.com/paritytech/substrate/pull/10291
- https://github.com/paritytech/substrate/pull/10313
- https://github.com/paritytech/substrate/pull/10394

This includes a new instance reuse mechanism in `wasmtime`: https://github.com/bytecodealliance/wasmtime/pull/3691; while they ultimately did not use my code directly what ended up in `wasmtime` was based on my work, where [in this PR we switch to that new instance reuse mechanism in Substrate](https://github.com/paritytech/substrate/pull/11232).

Extra software and hardware metrics:
- https://github.com/paritytech/substrate/pull/11062
- https://github.com/paritytech/substrate-telemetry/pull/464

### Investigative work

Leaking memory? Something's crashing randomly? Are you wasting so much CPU time that you don't need any extra heating in winter? Who ya gonna call? ~~Ghostbusters!~~ Probably me!

Besides direct contributions to Substrate and Polkadot I also do a lot of investigative work actually *finding* the issues, mostly related to memory, performance and soundness. Some examples of that:

- For [a memory leak crashing parachain nodes](https://github.com/paritytech/substrate/issues/11604): [my analysis](https://github.com/paritytech/substrate/issues/11604#issuecomment-1158752943) and [my PR with a fix](https://github.com/paritytech/substrate/pull/11694)
- For [memory-related nondeterminism triggering a panic within the runtime](https://github.com/paritytech/substrate/issues/10095): [my analysis](https://github.com/paritytech/substrate/issues/10095#issuecomment-966964447) and [my PR with a fix](https://github.com/paritytech/substrate/pull/10291)
- [Fix for a memory leak crashing RPC nodes](https://github.com/paritytech/substrate/pull/10454)
- [Found a dangerously long stack trace](https://github.com/paritytech/substrate/issues/8950) which was then fixed by Basti
- The contracts' benchmarks being up to 50% slower for no apparent reason; [my analysis (part 1)](https://github.com/paritytech/substrate/pull/12096#issuecomment-1238225600), [my analysis (part 2)](https://github.com/paritytech/substrate/pull/12096#issuecomment-1239560799)

I'm also the maintainer of [Bytehound](https://github.com/koute/bytehound), a memory profiler for Linux, which I regularily use on Substrate/Polkadot when investigating issues.

### Rank

~~Based on strict reading of the requirements as well as Gav's clarifications I apply for a rank of 1.~~

Updated to rank 2. (:

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by jacogr — APPROVED** [review]

**Review by rrtti — APPROVED** [review]

**Comment by bkchr** [comment]
Thinking about this again, I would probably approve II Dan for you. 

Let's see what the others are thinking about it. 

CC @jacogr @andresilva

**Comment by andresilva** [comment]
I would support rank 2 as well. I think @koute has proven deep knowledge on our WASM execution infrastructure and has done major contributions to improve it, also outside substrate (e.g. in wasmtime).

**Review by andresilva — APPROVED** [review]

**Comment by rrtti** [comment]
@andresilva @bkchr do we want to merge as it is or ask @koute to change the rank from I to II?

**Comment by jacogr** [comment]
Based on the WASM execution infrastructure changes alone, I'm also in favor of a II Dan here, so can take my approval as-is if others concur. (My initial rating was already for somebody that should climb up one exceptionally quickly based on the work performed in this specific environment).

I also think the existing work can be turned into the basis of a strong "one published long-form semi-technical article concerning Polkadot" which should be attacked reasonably soon to conform to "This leniancy, such as it is, should exist only for the initial bootstrapping phase. By the first continuation grading, the full expectations of the member's rank should be met for approval by voters."

**Comment by koute** [comment]
Thank you all for the vote of confidence. (: I've updated the rank to 2.

**Review by rrtti — APPROVED** [review]

**Comment by rrtti** [comment]
Hello @koute! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

**Comment by koute** [comment]
> Hello @koute! Please let us know your Element handle to add you to the Fellowship channel. Thank you!

Hey; it's `@jan:matrix.parity.io`

**Pull request merged**
